library verilog;
use verilog.vl_types.all;
entity conv_tb_v2 is
    generic(
        X_DIM           : integer := 1;
        Y_DIM           : integer := 358;
        DATA_WIDTH      : integer := 8;
        FIFO_DEPTH_WIDTH: integer := 9;
        actn_h          : integer := 360;
        actn_w          : integer := 1;
        actn_c          : integer := 1;
        filt_h          : integer := 3;
        filt_w          : integer := 1;
        filt_c          : integer := 1;
        num_filt        : integer := 128;
        stride          : integer := 1;
        out_h           : vl_notype;
        out_w           : vl_notype;
        out_c           : vl_notype;
        blk_h           : vl_notype;
        blk_w           : vl_notype;
        DEFAULT         : vl_logic_vector(0 to 2) := (Hi0, Hi0, Hi1);
        LD_WT_SRAM2PE   : vl_logic_vector(0 to 2) := (Hi0, Hi1, Hi0);
        LD_IF_SRAM2BUF  : vl_logic_vector(0 to 2) := (Hi0, Hi1, Hi1);
        LD_IF_BUF2PE    : vl_logic_vector(0 to 2) := (Hi1, Hi0, Hi0);
        DNNEXEC         : vl_logic_vector(0 to 2) := (Hi1, Hi0, Hi1);
        UNLD_OF_PE2BUF  : vl_logic_vector(0 to 2) := (Hi1, Hi1, Hi0);
        UNLD_OF_BUF2SRAM: vl_logic_vector(0 to 2) := (Hi1, Hi1, Hi1)
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of X_DIM : constant is 1;
    attribute mti_svvh_generic_type of Y_DIM : constant is 1;
    attribute mti_svvh_generic_type of DATA_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of FIFO_DEPTH_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of actn_h : constant is 1;
    attribute mti_svvh_generic_type of actn_w : constant is 1;
    attribute mti_svvh_generic_type of actn_c : constant is 1;
    attribute mti_svvh_generic_type of filt_h : constant is 1;
    attribute mti_svvh_generic_type of filt_w : constant is 1;
    attribute mti_svvh_generic_type of filt_c : constant is 1;
    attribute mti_svvh_generic_type of num_filt : constant is 1;
    attribute mti_svvh_generic_type of stride : constant is 1;
    attribute mti_svvh_generic_type of out_h : constant is 3;
    attribute mti_svvh_generic_type of out_w : constant is 3;
    attribute mti_svvh_generic_type of out_c : constant is 3;
    attribute mti_svvh_generic_type of blk_h : constant is 3;
    attribute mti_svvh_generic_type of blk_w : constant is 3;
    attribute mti_svvh_generic_type of DEFAULT : constant is 1;
    attribute mti_svvh_generic_type of LD_WT_SRAM2PE : constant is 1;
    attribute mti_svvh_generic_type of LD_IF_SRAM2BUF : constant is 1;
    attribute mti_svvh_generic_type of LD_IF_BUF2PE : constant is 1;
    attribute mti_svvh_generic_type of DNNEXEC : constant is 1;
    attribute mti_svvh_generic_type of UNLD_OF_PE2BUF : constant is 1;
    attribute mti_svvh_generic_type of UNLD_OF_BUF2SRAM : constant is 1;
end conv_tb_v2;
